[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
name = "csvx"
version = "4.0.0"

[dependencies]
chrono = "0.3.0"
clap = "2.23.3"
csv = "0.15.0"
lazy_static = "0.2.8"
regex = "0.2.1"
safe_unwrap = "0.1.1"
